server:
  port: 82

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-integracion_instituciones-service
          uri: lb://ms-integracion_instituciones-service
          predicates:
            - Path=/ConvenioAcuerdo/**, /DatosCompartidos/**, /InstitucionExterna/**, /OtraUGEL/**
        - id: ms-monitoreo_asistencia-service
          uri: lb://ms-monitoreo_asistencia
          predicates:
            - Path=/Clase/**, /Estudiante/**, /RegistroAsistencia/**
        - id: ms-soporte_asistencia-service
          uri: lb://ms-soporte_asistencia-service
          predicates:
            - Path=/HistorialSoporte/**, /Incidente/**, /SolicitudSoporte/**

        - id: ms-gestion_infraestructura-service
          uri: lb://ms-gestion_infraestructura-service
          predicates:
            - Path=/aula/**, /edificio/**, /equipo/** , /mantenimiento/**

        - id: ms-gestion_financiera-service
          uri: lb://ms-gestion_financiera-service
          predicates:
            - Path=/cuenta/**, /egreso/**, /ingreso/** , /transaccion/**

        - id: ms-comunicaciones_alertas-service
          uri: lb://ms-comunicaciones_alertas-service
          predicates:
            - Path=/alerta/**, /grupo/**, /mensaje/** , /miembro_grupo/**

        - id: ms-gestion_docentes-service
          uri: lb://ms-gestion_docentes-service
          predicates:
            - Path=/Asignatura/**, /Docente/**, /Evaluación/**

        - id: ms-gestion_eventos_actividades-service
          uri: lb://ms-gestion_eventos_actividades-service
          predicates:
            - Path=/Actividad/**, /Evento/**, /Participante/**, /RecursoNecesario/**

        - id: ms-planificacion_curricular-service
          uri: lb://ms-planificacion_curricular-service
          predicates:
            - Path=/ContenidoCurricular/**, /Curso/**, /DocenteCurso/**, /EstudianteCurso/**, /PlanEstudios/**