server:
  port: 82

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-integracion_instituciones-service
          uri: lb://ms-integracion_instituciones-service
          predicates:
            - Path=/ConvenioAcuerdo/**, /DatosCompartidos/**, /InstitucionExterna/**, /OtraUGEL/**
        - id: ms-monitoreo_asistencia-service
          uri: lb://ms-monitoreo_asistencia
          predicates:
            - Path=/Clase/**, /Estudiante/**, /RegistroAsistencia/**
        - id: ms-soporte_asistencia-service
          uri: lb://ms-soporte_asistencia-service
          predicates:
            - Path=/HistorialSoporte/**, /Incidente/**, /SolicitudSoporte/**

        - id: ms-gestion_infraestructura-service
          uri: lb://ms-gestion_infraestructura-service
          predicates:
            - Path=/Aula/**, /Edificio/**, /Equipo/** , /Mantenimiento/**

        - id: ms-gestion_financiera-service
          uri: lb://ms-gestion_financiera-service
          predicates:
            - Path=/Cuenta/**, /Egreso/**, /Ingreso/** , /Transaccion/**

